spring.application.name=server
spring.datasource.url=jdbc:mysql://localhost:3306/schoolpass
spring.datasource.username=buscare
spring.datasource.password=buscare123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080
